---
stages:
  - deploy
  - test

deploy:
  tags:
    - production
  stage: deploy
  script:
    - sudo salt '*' state.apply

test:
  tags:
    - production
  stage: test
  script:
    - sudo salt '*' cmd.run 'net show bgp summary json' | grep '"state":"Idle"'
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /test-bgp/

